name: app3
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive:
  hive_flutter:
  path_provider:
  image_picker:
  flutter_spinkit:

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator:
  build_runner:

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/imgs/

  uses-material-design: true
